# DEV build helper. Embed presentation sources into the existing customer manager file.
[CmdletBinding()]
param(
    [string]$ManagerPath = '',
    [string]$RecipePath = '',
    [switch]$Check
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version 2.0
if ($PSVersionTable.PSVersion.Major -ne 5 -or $PSVersionTable.PSVersion.Minor -lt 1 -or
    ($PSVersionTable.ContainsKey('PSEdition') -and $PSVersionTable.PSEdition -eq 'Core')) {
    throw 'Use Windows PowerShell 5.1 (powershell.exe), not pwsh.'
}
if ([string]::IsNullOrWhiteSpace($ManagerPath)) { $ManagerPath = Join-Path $PSScriptRoot '..\..\ui\p0158.ps1' }
if ([string]::IsNullOrWhiteSpace($RecipePath)) { $RecipePath = Join-Path $PSScriptRoot 'recipes\bitwrecked-quiet.json' }

function Read-PreservedText {
    param([string]$Path)
    $bytes = [IO.File]::ReadAllBytes($Path)
    $skip = 0
    $encoding = New-Object Text.UTF8Encoding($false, $true)
    # Check UTF-32 before UTF-16 because the little-endian BOM shares its prefix.
    if ($bytes.Length -ge 4 -and $bytes[0] -eq 0xFF -and $bytes[1] -eq 0xFE -and $bytes[2] -eq 0 -and $bytes[3] -eq 0) {
        $encoding = New-Object Text.UTF32Encoding($false, $false, $true); $skip = 4
    } elseif ($bytes.Length -ge 4 -and $bytes[0] -eq 0 -and $bytes[1] -eq 0 -and $bytes[2] -eq 0xFE -and $bytes[3] -eq 0xFF) {
        $encoding = New-Object Text.UTF32Encoding($true, $false, $true); $skip = 4
    } elseif ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) {
        $skip = 3
    } elseif ($bytes.Length -ge 2 -and $bytes[0] -eq 0xFF -and $bytes[1] -eq 0xFE) {
        $encoding = New-Object Text.UnicodeEncoding($false, $false, $true); $skip = 2
    } elseif ($bytes.Length -ge 2 -and $bytes[0] -eq 0xFE -and $bytes[1] -eq 0xFF) {
        $encoding = New-Object Text.UnicodeEncoding($true, $false, $true); $skip = 2
    }
    try { $value = $encoding.GetString($bytes, $skip, $bytes.Length - $skip) }
    catch { throw 'Manager encoding is not supported safely. Use UTF-8 or BOM-marked Unicode.' }
    $preamble = New-Object byte[] $skip
    if ($skip -gt 0) { [Array]::Copy($bytes, 0, $preamble, 0, $skip) }
    [pscustomobject]@{ Text = $value; Encoding = $encoding; Preamble = $preamble; OriginalBytes = $bytes }
}

function Get-EmbeddedLiteral {
    param([string]$Text, [string]$Newline, [string]$Name)
    $normalized = [regex]::Replace($Text, '\r\n|\r|\n', $Newline).TrimEnd([char[]]"`r`n")
    # Never permit a literal to close its own single-quoted PowerShell here-string.
    if ([regex]::IsMatch($normalized, "(?m)^'@")) { throw "$Name contains an unsafe here-string terminator." }
    return $normalized
}

$managerFullPath = [IO.Path]::GetFullPath($ManagerPath)
if ([IO.Path]::GetExtension($managerFullPath) -ine '.ps1') { throw 'ManagerPath must identify a .ps1 file.' }
$recipeFullPath = [IO.Path]::GetFullPath($RecipePath)
$controlsPath = Join-Path $PSScriptRoot 'NativeControls.cs'
Import-Module (Join-Path $PSScriptRoot 'Recipes.psm1') -Force
$recipe = Get-DesignRecipe -Path $recipeFullPath -Target Manager
$recipeHash = (Get-FileHash -LiteralPath $recipeFullPath -Algorithm SHA256).Hash
$controlsHash = (Get-FileHash -LiteralPath $controlsPath -Algorithm SHA256).Hash
$manager = Read-PreservedText -Path $managerFullPath
$newlineMatch = [regex]::Match($manager.Text, '\r\n|\n|\r')
$newline = if ($newlineMatch.Success) { $newlineMatch.Value } else { "`r`n" }
# Windows PowerShell 5.1 reads BOM-less scripts with the system ANSI encoding.
# Escape each non-ASCII UTF-16 code unit inside JSON, preserving script encoding.
$recipeJson = [regex]::Replace(($recipe | ConvertTo-Json -Depth 16), '[^\x00-\x7F]',
    [Text.RegularExpressions.MatchEvaluator]{ param($match) '\u{0:x4}' -f [int][char]$match.Value[0] })
$recipeLiteral = Get-EmbeddedLiteral -Text $recipeJson -Newline $newline -Name 'Recipe'
$controlsLiteral = Get-EmbeddedLiteral -Text ([IO.File]::ReadAllText($controlsPath)) -Newline $newline -Name 'NativeControls.cs'

$beginMarker = '# BEGIN HRS GENERATED NATIVE DESIGN'
$endMarker = '# END HRS GENERATED NATIVE DESIGN'
$lines = @(
    $beginMarker,
    '# Generated by dev/tools/NativeGraphics/Sync-ManagerDesign.ps1; edit the recipe or controls source, then sync.',
    ('$script:hrsDesignRecipeSha256 = ''' + $recipeHash + ''''),
    ('$script:hrsDesignControlsSha256 = ''' + $controlsHash + ''''),
    '$script:hrsDesignRecipeJson = @''',
    $recipeLiteral,
    '''@',
    '$script:hrsDesignRecipe = ConvertFrom-Json -InputObject $script:hrsDesignRecipeJson -ErrorAction Stop',
    '$script:hrsDesignControlsSource = @''',
    $controlsLiteral,
    '''@',
    'if (-not (''BitWrecked.NativeGraphics.V1.SurfacePanel'' -as [type])) {',
    '    Add-Type -TypeDefinition $script:hrsDesignControlsSource -ReferencedAssemblies System.Drawing,System.Windows.Forms -ErrorAction Stop',
    '}',
    $endMarker
)
$region = ($lines -join $newline) + $newline
$beginMatches = [regex]::Matches($manager.Text, '(?m)^' + [regex]::Escape($beginMarker) + '(?=\r?$)')
$endMatches = [regex]::Matches($manager.Text, '(?m)^' + [regex]::Escape($endMarker) + '(?=\r?$)')
$existing = $false
if ($beginMatches.Count -eq 0 -and $endMatches.Count -eq 0) {
    $initPattern = '(?m)^Add-Type -AssemblyName System\.Windows\.Forms\r?\nAdd-Type -AssemblyName System\.Drawing(?:\r?\n|\z)'
    $initMatches = [regex]::Matches($manager.Text, $initPattern)
    if ($initMatches.Count -ne 1) { throw 'Cannot identify the unique native WinForms/Drawing initialization block.' }
    $offset = $initMatches[0].Index + $initMatches[0].Length
    $prefix = $manager.Text.Substring(0, $offset)
    if (-not $prefix.EndsWith($newline)) { $prefix += $newline }
    $updated = $prefix + $region + $manager.Text.Substring($offset)
} elseif ($beginMatches.Count -eq 1 -and $endMatches.Count -eq 1 -and $endMatches[0].Index -gt $beginMatches[0].Index) {
    $existing = $true
    $offset = $beginMatches[0].Index
    $after = $endMatches[0].Index + $endMarker.Length
    if ($manager.Text.Substring($after).StartsWith("`r`n")) { $after += 2 }
    elseif ($after -lt $manager.Text.Length -and ($manager.Text[$after] -eq "`n" -or $manager.Text[$after] -eq "`r")) { $after++ }
    $updated = $manager.Text.Substring(0, $offset) + $region + $manager.Text.Substring($after)
} else {
    throw 'Generated design markers are incomplete, duplicated or out of order; no manager changes were written.'
}

# Check the complete new source before writing it; parsing never runs recipe text.
$parseTokens = $null; $parseErrors = $null
[void][Management.Automation.Language.Parser]::ParseInput($updated, [ref]$parseTokens, [ref]$parseErrors)
if ($parseErrors.Count -gt 0) { throw ('Generated manager does not parse: ' + ($parseErrors.Message -join '; ')) }
$current = $existing -and [string]::Equals($manager.Text, $updated, [StringComparison]::Ordinal)
if (-not $Check -and -not $current) {
    $body = $manager.Encoding.GetBytes($updated)
    $outputBytes = New-Object byte[] ($manager.Preamble.Length + $body.Length)
    if ($manager.Preamble.Length -gt 0) { [Array]::Copy($manager.Preamble, 0, $outputBytes, 0, $manager.Preamble.Length) }
    [Array]::Copy($body, 0, $outputBytes, $manager.Preamble.Length, $body.Length)
    [IO.File]::WriteAllBytes($managerFullPath, $outputBytes)
}
[pscustomobject]@{
    ManagerPath = $managerFullPath
    RecipeId = $recipe.id
    RecipeSha256 = $recipeHash
    ControlsSha256 = $controlsHash
    Status = if ($current) { 'Current' } elseif ($Check) { if ($existing) { 'Stale' } else { 'Missing' } } else { 'Updated' }
    Changed = [bool](-not $Check -and -not $current)
    Embedded = [bool]($existing -or -not $Check)
}
